#!/usr/bin/env node
/* =========================================================================
 scripts/fetch-fonts.js
 One-off helper that self-hosts the site's web fonts.

 Downloads the WOFF2 files for the fonts styles.css uses (Manrope,
 Plus Jakarta Sans, IBM Plex Mono) from Google Fonts into
 public/resources/fonts/, and writes public/resources/css/fonts.css with
 matching @font-face rules (imported at the top of styles.css). After it
 has run once, pages load fonts from this server only — no request to
 Google at page-load time.

 Only the "latin" and "latin-ext" subsets are kept (latin-ext covers the
 ₹ sign). Re-run it whenever the font list below changes:

     npm run fonts

 Requires Node 18+ (global fetch) and internet access for this one run.
 All three families are licensed under the SIL Open Font License 1.1,
 which allows self-hosting.
 ========================================================================= */

const fs = require('node:fs');
const path = require('node:path');

// Same families/weights the pages previously requested from Google.
// Manrope and Plus Jakarta Sans are variable fonts, so a weight range
// gives one file per subset instead of one per weight.
const FAMILIES = [
    'family=Manrope:wght@500..800',
    'family=Plus+Jakarta+Sans:wght@400..800',
    'family=IBM+Plex+Mono:wght@400;500;600'
];
const KEEP_SUBSETS = ['latin', 'latin-ext'];

const CSS_URL = 'https://fonts.googleapis.com/css2?' + FAMILIES.join('&') + '&display=swap';
// Google only serves WOFF2 URLs to browsers it recognises as modern.
const USER_AGENT = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0 Safari/537.36';

const ROOT = path.join(__dirname, '..');
const FONTS_DIR = path.join(ROOT, 'public', 'resources', 'fonts');
const FONTS_CSS = path.join(ROOT, 'public', 'resources', 'css', 'fonts.css');

function slug(str) {
    return String(str).toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
}

function prop(block, name) {
    const m = block.match(new RegExp(name + '\\s*:\\s*([^;]+);'));
    return m ? m[1].trim() : '';
}

/** Splits Google's CSS into {subset, family, style, weight, url, range}. */
function parseFontFaces(css) {
    const faces = [];
    const re = /\/\*\s*([\w-]+)\s*\*\/\s*@font-face\s*\{([^}]*)\}/g;
    let m;
    while ((m = re.exec(css)) !== null) {
        const block = m[2];
        const url = (block.match(/url\(([^)]+)\)/) || [])[1];
        if (!url)
            continue;
        faces.push({
            subset: m[1],
            family: prop(block, 'font-family').replace(/['"]/g, ''),
            style: prop(block, 'font-style') || 'normal',
            weight: prop(block, 'font-weight') || '400',
            url: url.replace(/['"]/g, ''),
            range: prop(block, 'unicode-range')
        });
    }
    return faces;
}

async function download(url) {
    const res = await fetch(url, {headers: {'User-Agent': USER_AGENT}});
    if (!res.ok)
        throw new Error(`HTTP ${res.status} for ${url}`);
    return Buffer.from(await res.arrayBuffer());
}

async function main() {
    console.log('Fetching font CSS from Google Fonts…');
    const cssRes = await fetch(CSS_URL, {headers: {'User-Agent': USER_AGENT}});
    if (!cssRes.ok)
        throw new Error(`HTTP ${cssRes.status} for ${CSS_URL}`);
    const faces = parseFontFaces(await cssRes.text()).filter(f => KEEP_SUBSETS.includes(f.subset));
    if (faces.length === 0)
        throw new Error('No latin/latin-ext @font-face rules found in the Google Fonts response.');

    fs.mkdirSync(FONTS_DIR, {recursive: true});

    const fileByUrl = new Map();
    const rules = [];
    let bytes = 0;

    for (const f of faces) {
        let file = fileByUrl.get(f.url);
        if (!file) {
            // e.g. manrope-500-800-normal-latin.woff2, ibm-plex-mono-400-normal-latin-ext.woff2
            file = `${slug(f.family)}-${slug(f.weight)}-${f.style}-${f.subset}.woff2`;
            const data = await download(f.url);
            fs.writeFileSync(path.join(FONTS_DIR, file), data);
            fileByUrl.set(f.url, file);
            bytes += data.length;
            console.log(`  saved ${file} (${(data.length / 1024).toFixed(1)} KB)`);
        }
        rules.push(`/* ${f.family} ${f.weight} ${f.style} — ${f.subset} */
@font-face {
    font-family: '${f.family}';
    font-style: ${f.style};
    font-weight: ${f.weight};
    font-display: swap;
    src: url('../fonts/${file}') format('woff2');${f.range ? `\n    unicode-range: ${f.range};` : ''}
}`);
    }

    const header = `/* =========================================================================
   fonts.css — GENERATED by scripts/fetch-fonts.js (npm run fonts).
   Self-hosted web fonts; do not edit by hand, re-run the script instead.
   Manrope, Plus Jakarta Sans, IBM Plex Mono — SIL Open Font License 1.1.
   ========================================================================= */

`;
    fs.writeFileSync(FONTS_CSS, header + rules.join('\n\n') + '\n');

    console.log(`\nDone: ${fileByUrl.size} font files (${(bytes / 1024).toFixed(0)} KB) in public/resources/fonts/`);
    console.log('Wrote public/resources/css/fonts.css');
}

main().catch(err => {
    console.error('\nFont download failed:', err.message);
    process.exit(1);
});
